name: Deploy
on: [workflow_dispatch]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: azure/k8s-set-context@v1
      with:
        method: service-account
        k8s-url: ${{ secrets.K8S_URL }}
        k8s-secret: ${{ secrets.K8S_SECRET }}

    - uses: Azure/k8s-deploy@v1.3
      with:
        namespace: 'weight-logger'
        manifests: |
            k8s-manifests/service.yaml
            k8s-manifests/deployment.yaml
            k8s-manifests/ingress.yaml
